-- agregar campo direccion a la TABLA clientes
ALTER TABLE clientes ADD COLUMN direccion VARCHAR(25);

-- AGREGAR CAMPO FECHA A LA TABLA SERVICIOS
ALTER TABLE servicios ADD COLUMN fecha DATE;

-- AGREGAR CAMPO DIRECCION A LA TABLA PLOMEROS
ALTER TABLE facturas ADD COLUMN direccion VARCHAR(255);

-- AGREGAR CAMPO direccion A LA TABLA facturas
ALTER TABLE facturas ADD COLUMN direccion VARCHAR(255);

-- MODIFICAR LA TABLA PAGOS PARA QUE EL CAMPO FACTURA_ID SEA NO NULO
ALTER TABLE pagos MODIFY COLUMN factura_id INT NOT NULL;
